---
openapi: 3.0.1
info:
  title: SDP Platform API
  version: v1
  description: Scale Development Platform - RESTful API Documentation
  contact:
    name: Aybüke TURGUN
    email: aybuket@example.com
paths:
  "/api/v1/users":
    get:
      summary: List all users
      tags:
      - Users
      description: Returns all users in the system
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/User"
                required:
                - success
                - message
                - data
    post:
      summary: Create a user
      tags:
      - Users
      description: Creates a new user
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                    name:
                      type: string
                    role:
                      type: integer
                    credit_balance:
                      type: integer
                  required:
                  - email
                  - password
                  - password_confirmation
                  - name
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: User ID
      required: true
      schema:
        type: string
    get:
      summary: Show a user
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    "$ref": "#/components/schemas/User"
        '404':
          description: not found
servers:
- url: http://localhost:3000
  description: Development server
- url: https://api.sdp-platform.com
  description: Production server
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        name:
          type: string
        role:
          type: string
          enum:
          - researcher
          - clinician
          - student
          - admin
        credit_balance:
          type: integer
        organization:
          type: string
        locale:
          type: string
      required:
      - id
      - email
      - name
      - role
